// Generated by gencpp from file package1/xsxx.msg
// DO NOT EDIT!


#ifndef PACKAGE1_MESSAGE_XSXX_H
#define PACKAGE1_MESSAGE_XSXX_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace package1
{
template <class ContainerAllocator>
struct xsxx_
{
  typedef xsxx_<ContainerAllocator> Type;

  xsxx_()
    : num(0)
    , name()
    , sex(0)
    , age(0)  {
    }
  xsxx_(const ContainerAllocator& _alloc)
    : num(0)
    , name(_alloc)
    , sex(0)
    , age(0)  {
  (void)_alloc;
    }



   typedef int32_t _num_type;
  _num_type num;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef uint8_t _sex_type;
  _sex_type sex;

   typedef int32_t _age_type;
  _age_type age;





  typedef boost::shared_ptr< ::package1::xsxx_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::package1::xsxx_<ContainerAllocator> const> ConstPtr;

}; // struct xsxx_

typedef ::package1::xsxx_<std::allocator<void> > xsxx;

typedef boost::shared_ptr< ::package1::xsxx > xsxxPtr;
typedef boost::shared_ptr< ::package1::xsxx const> xsxxConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::package1::xsxx_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::package1::xsxx_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace package1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'package1': ['/home/qxh/mine3/src/package1/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::package1::xsxx_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::package1::xsxx_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::package1::xsxx_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::package1::xsxx_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package1::xsxx_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package1::xsxx_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::package1::xsxx_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3498295c192fb06e0bc39c0f48535271";
  }

  static const char* value(const ::package1::xsxx_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3498295c192fb06eULL;
  static const uint64_t static_value2 = 0x0bc39c0f48535271ULL;
};

template<class ContainerAllocator>
struct DataType< ::package1::xsxx_<ContainerAllocator> >
{
  static const char* value()
  {
    return "package1/xsxx";
  }

  static const char* value(const ::package1::xsxx_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::package1::xsxx_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 num\n\
string name\n\
char sex\n\
int32 age\n\
";
  }

  static const char* value(const ::package1::xsxx_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::package1::xsxx_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num);
      stream.next(m.name);
      stream.next(m.sex);
      stream.next(m.age);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct xsxx_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::package1::xsxx_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::package1::xsxx_<ContainerAllocator>& v)
  {
    s << indent << "num: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "sex: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sex);
    s << indent << "age: ";
    Printer<int32_t>::stream(s, indent + "  ", v.age);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PACKAGE1_MESSAGE_XSXX_H
