// Generated by gencpp from file package1/xx.msg
// DO NOT EDIT!


#ifndef PACKAGE1_MESSAGE_XX_H
#define PACKAGE1_MESSAGE_XX_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace package1
{
template <class ContainerAllocator>
struct xx_
{
  typedef xx_<ContainerAllocator> Type;

  xx_()
    : value(0)
    , number(0)  {
    }
  xx_(const ContainerAllocator& _alloc)
    : value(0)
    , number(0)  {
  (void)_alloc;
    }



   typedef int32_t _value_type;
  _value_type value;

   typedef int32_t _number_type;
  _number_type number;





  typedef boost::shared_ptr< ::package1::xx_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::package1::xx_<ContainerAllocator> const> ConstPtr;

}; // struct xx_

typedef ::package1::xx_<std::allocator<void> > xx;

typedef boost::shared_ptr< ::package1::xx > xxPtr;
typedef boost::shared_ptr< ::package1::xx const> xxConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::package1::xx_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::package1::xx_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace package1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'package1': ['/home/qxh/mine3/src/package1/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::package1::xx_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::package1::xx_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::package1::xx_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::package1::xx_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package1::xx_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package1::xx_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::package1::xx_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ee77c94eccf43256662c380c97a6bc35";
  }

  static const char* value(const ::package1::xx_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xee77c94eccf43256ULL;
  static const uint64_t static_value2 = 0x662c380c97a6bc35ULL;
};

template<class ContainerAllocator>
struct DataType< ::package1::xx_<ContainerAllocator> >
{
  static const char* value()
  {
    return "package1/xx";
  }

  static const char* value(const ::package1::xx_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::package1::xx_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 value\n\
int32 number\n\
";
  }

  static const char* value(const ::package1::xx_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::package1::xx_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
      stream.next(m.number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct xx_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::package1::xx_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::package1::xx_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<int32_t>::stream(s, indent + "  ", v.value);
    s << indent << "number: ";
    Printer<int32_t>::stream(s, indent + "  ", v.number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PACKAGE1_MESSAGE_XX_H
